apiVersion: opentofu.m.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ include "crossplane-swa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crossplane-swa.labels" . | nindent 4 }}
    managed-by: crossplane-opentofu
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: azure-avm
  forProvider:
    source: Remote
    module: git::https://github.com/Azure/terraform-azurerm-avm-res-web-staticsite.git?ref=v0.6.2
    remotePullPolicy: IfNotPresent
    vars:
      - key: name
        value: {{ .Release.Name }}
      - key: location
        value: {{ .Values.location }}
      - key: resource_group_name
        value: "rg-crossplane-test"
      - key: enable_telemetry
        value: "false"
    {{- with .Values.tags }}
    varmap:
      tags:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  writeConnectionSecretToRef:
    name: {{ .Release.Name }}
