apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-starter.fullname" . }}
  labels:
    {{- include "container-starter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "container-starter.selectorLabels" . | nindent 4 }}
