apiVersion: opentofu.m.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ include "crossplane-workspace.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crossplane-workspace.labels" . | nindent 4 }}
    managed-by: crossplane-opentofu
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: azure-avm
  forProvider:
    source: Remote
    module: git::https://github.com/Azure/terraform-azurerm-avm-res-resources-resourcegroup.git?ref=v0.4.0
    remotePullPolicy: IfNotPresent
    vars:
      - key: name
        value: {{ .Values.name }}
      - key: location
        value: {{ .Values.location }}
      - key: enable_telemetry
        value: "false"
    {{- with .Values.tags }}
    varmap:
      tags:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  writeConnectionSecretToRef:
    name: {{ .Values.name }}
